import manImg1 from "../assets/Images/joseph-unsplash.jpg";
import manImg2 from "../assets/Images/blackSmilingMan.PNG";
import manImg3 from "../assets/Images/blackSmilingMan2.PNG";
import manImg4 from "../assets/Images/blackSmilingMan3.PNG";
import charlesImg from "../assets/Images/Profile.png";
import manImg5 from "../assets/Images/blackSmilingMan4.PNG";
import manImg6 from "../assets/Images/blackSmilingMan5.PNG";

import womanImg1 from "../assets/Images/art-unsplash.jpg";
import womanImg2 from "../assets/Images/prince-unsplash.jpg";
import womanImg3 from "../assets/Images/blackWoman.PNG";
import womanImg4 from "../assets/Images/blackWoman2.PNG";
import womanImg5 from "../assets/Images/blackWoman3.PNG";
import womanImg6 from "../assets/Images/blackWoman4.PNG";
import womanImg7 from "../assets/Images/blackWoman5.PNG";

const Frontend = {
  track: "Frontend",
  interns: [
    {
      id: 1,
      firstName: "TIMOTHY",
      lastName: "ACHONU",
      imgSrc: manImg6,
      bonus: 1,
      strikes: 0,
      attendance: 100,
      appraisals: {
        one: 4,
        two: 4.1,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 10,
        task3: 7.5,
        task4: 9.2,
        task5: 8,
        task6: 8.5,
        task7: 7,
        task8: 10,
        task9: 7,
        task10: "",
      },
      powerRanking: "2126",
    },
    {
      id: 2,
      firstName: "SOCHIMA",
      lastName: "ONAH",
      imgSrc: manImg2,
      bonus: 0,
      strikes: 0,
      attendance: 83,
      appraisals: {
        one: 4,
        two: 4.0,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 10,
        task3: 6.5,
        task4: 9.5,
        task5: 10,
        task6: 8.5,
        task7: 10,
        task8: 5,
        task9: 9.9,
        task10: "",
      },
      powerRanking: "2081",
    },
    {
      id: 3,
      firstName: "KIZITO",
      lastName: "CHINAZO",
      imgSrc: manImg3,
      bonus: 0,
      strikes: 0,
      attendance: 93,
      appraisals: {
        one: 4,
        two: 4.1,
        three: "",
      },
      tasks: {
        task1: 8,
        task2: 8,
        task3: 9.7,
        task4: 8.5,
        task5: 8.5,
        task6: 7,
        task7: 9,
        task8: 8,
        task9: 9.5,
        task10: "",
      },
      powerRanking: "2058",
    },
    {
      id: 4,
      firstName: "NKEMDILI",
      lastName: "EZIKE",
      imgSrc: womanImg1,
      bonus: 0,
      strikes: 0,
      attendance: 100,
      appraisals: {
        one: 4,
        two: 4.1,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 7,
        task3: 6.7,
        task4: 7.9,
        task5: 10,
        task6: 8,
        task7: 9,
        task8: 9,
        task9: 7,
        task10: "",
      },
      powerRanking: "2053",
    },
    {
      id: 5,
      firstName: "CHARLES",
      lastName: "ORIIH",
      imgSrc: charlesImg,
      bonus: 0,
      strikes: 1,
      attendance: 86,
      appraisals: {
        one: 4,
        two: 4.2,
        three: "",
      },
      tasks: {
        task1: 8,
        task2: 10,
        task3: 7.3,
        task4: 7.8,
        task5: 10,
        task6: 6.2,
        task7: 10,
        task8: 10,
        task9: 8,
        task10: "",
      },
      powerRanking: "2043",
    },
    {
      id: 6,
      firstName: "CHUKWUEBUKA",
      lastName: "EDWARD",
      imgSrc: manImg5,
      bonus: 0,
      strikes: 1,
      attendance: 100,
      appraisals: {
        one: 4,
        two: 4.4,
        three: "",
      },
      tasks: {
        task1: 7,
        task2: 6,
        task3: 7.2,
        task4: 8,
        task5: 8,
        task6: 9,
        task7: 10,
        task8: 10,
        task9: 8,
        task10: "",
      },
      powerRanking: "2022",
    },

    {
      id: 7,
      firstName: "CHINEDU",
      lastName: "IBELACHI",
      imgSrc: manImg6,
      bonus: 0,
      strikes: 0,
      attendance: 100,
      appraisals: {
        one: 4,
        two: 4.0,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 9,
        task3: 8,
        task4: 5.9,
        task5: 6.5,
        task6: 7,
        task7: 9,
        task8: 10,
        task9: 7,
        task10: "",
      },
      powerRanking: "2009",
    },

    {
      id: 8,
      firstName: "CHIMAOBI",
      lastName: "CHUKWUEGBO",
      imgSrc: manImg1,
      bonus: 0,
      strikes: 0,
      attendance: 93,
      appraisals: {
        one: 4,
        two: 3.5,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 10,
        task3: 7.5,
        task4: 9,
        task5: 6,
        task6: 7.5,
        task7: 7,
        task8: 8.5,
        task9: 7.5,
        task10: "",
      },
      powerRanking: "1982",
    },

    {
      id: 9,
      firstName: "CHIOMA",
      lastName: "UGWUODO",
      imgSrc: womanImg2,
      bonus: 0,
      strikes: 1,
      attendance: 83,
      appraisals: {
        one: 3,
        two: 3.9,
        three: "",
      },
      tasks: {
        task1: 8,
        task2: 10,
        task3:  7.8,
        task4:  4,
        task5: 9.8,
        task6: 8,
        task7: 10,
        task8: 8,
        task9: 9.5,
        task10: "",
      },
      powerRanking: "1963",
    },

    {
      id: 10,
      firstName: "ONYINYECHI",
      lastName: "OKEKE",
      imgSrc: womanImg3,
      bonus: 0,
      strikes: 0,
      attendance: 93,
      appraisals: {
        one: 4,
        two: 3.9,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 8,
        task3: 7,
        task4: 5.7,
        task5: 7,
        task6: 8,
        task7: 9,
        task8: 9,
        task9: 7,
        task10: "",
      },
      powerRanking: "1943",
    },

    {
      id: 11,
      firstName: "JACHIKE",
      lastName: "VICTOR",
      imgSrc: manImg4,
      bonus: 0,
      strikes: 0,
      attendance: 83,
      appraisals: {
        one: 4,
        two: 4.1,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 8,
        task3: 7,
        task4: 8.2,
        task5: 7,
        task6: 4,
        task7: 10,
        task8: 9,
        task9: 8.5,
        task10: "",
      },
      powerRanking: "1930",
    },

    {
      id: 12,
      firstName: "SAMSON",
      lastName: "ADERONMU",
      imgSrc: manImg1,
      bonus: 0,
      strikes: 0,
      attendance: 100,
      appraisals: {
        one: 4,
        two: 3.8,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 10,
        task3: 6.5,
        task4: 7.5,
        task5: 8.2,
        task6: 8,
        task7: 7,
        task8: 2,
        task9: 8.5,
        task10: "",
      },
      powerRanking: "1910",
    },

    {
      id: 13,
      firstName: "OJUMOOLA",
      lastName: "AKINYODE",
      imgSrc: womanImg4,
      bonus: 0,
      strikes: 0,
      attendance: 86,
      appraisals: {
        one: 4,
        two: 4.2,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 6,
        task3: 5.5,
        task4: 7.5,
        task5: 9.5,
        task6: 8,
        task7: 9.5,
        task8: 6,
        task9: 6.5,
        task10: "",
      },
      powerRanking: "1878",
    },

    {
      id: 14,
      firstName: "DANIEL",
      lastName: "OCHI",
      imgSrc: manImg1,
      bonus: 1,
      strikes: 0,
      attendance: 88,
      appraisals: {
        one: 4,
        two: 4.1,
        three: "",
      }, 
      tasks: {
        task1: 7,
        task2: 7,
        task3: 6,
        task4: 7.8,
        task5: 5,
        task6: 7.5,
        task7: 9,
        task8: 10,
        task9: 7.5,
        task10: "",
      },
      powerRanking: "1870",
    },

    {
      id: 15,
      firstName: "JOHN",
      lastName: "OKORIE",
      imgSrc: manImg1,
      bonus: 1,
      strikes: 1,
      attendance: 74,
      appraisals: {
        one: 3,
        two: 3.7,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 9,
        task3: 8.3,
        task4: 7.6,
        task5: 7,
        task6: 8,
        task7: 10,
        task8: 10,
        task9: 0,
        task10: "",
      },
      powerRanking: "1837",
    },

    {
      id: 16,
      firstName: "KENECHUKWU",
      lastName: "CHIDUME",
      imgSrc: manImg1,
      bonus: 0,
      strikes: 0,
      attendance: 93,
      appraisals: {
        one: 4,
        two: 3.7,
        three: "",
      },
      tasks: {
        task1: 8,
        task2: 10,
        task3: 7.5,
        task4: 9,
        task5: 8,
        task6: 7,
        task7: 8,
        task8: 0,
        task9: 7.5,
        task10: "",
      },
      powerRanking: "1825",
    },

    {
      id: 17,
      firstName: "EBUBECHUKWU",
      lastName: "EZIKE",
      imgSrc: womanImg5,
      bonus: 0,
      strikes: 0,
      attendance: 95,
      appraisals: {
        one: 4,
        two: 3.8,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 9,
        task3: 8,
        task4: 7.3,
        task5: 7,
        task6: 4,
        task7: 7,
        task8: 6,
        task9: 6,
        task10: "",
      },
      powerRanking: "1822",
    },

    {
      id: 18,
      firstName: "EMMANUEL",
      lastName: "NWAFOR",
      imgSrc: manImg1,
      bonus: 0,
      strikes: 0,
      attendance: 100,
      appraisals: {
        one: 3,
        two: 4.1,
        three: "",
      },
      tasks: {
        task1: 5,
        task2: 4,
        task3: 6.6,
        task4: 7.8,
        task5: 7,
        task6: 6,
        task7: 10,
        task8: 10,
        task9: 7.5,
        task10: "",
      },
      powerRanking: "1821",
    },

    {
      id: 19,
      firstName: "GOODNEWS",
      lastName: "OFO",
      imgSrc: womanImg6,
      bonus: 0,
      strikes: 1,
      attendance: 88,
      appraisals: {
        one: 4,
        two: 3.9,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 5,
        task3: 4.2,
        task4: 7.1,
        task5: 5.5,
        task6: 6,
        task7: 9.5,
        task8: 9,
        task9: 9.5,
        task10: "",
      },
      powerRanking: "1817",
    },

    {
      id: 20,
      firstName: "AMARACHUKWU",
      lastName: "NWEKE",
      imgSrc: womanImg7,
      bonus: 1,
      strikes: 0,
      attendance: 100,
      appraisals: {
        one: 4,
        two: 4.3,
        three: "",
      },
      tasks: {
        task1: 10,
        task2: 8,
        task3: 5.1,
        task4: 7.5,
        task5: 6.5,
        task6: 6.5,
        task7: 6,
        task8: 6,
        task9: 6,
        task10: "",
      },
      powerRanking: "1817",
    }
  ],
};

export default Frontend;
